[profile.default]
src = 'contracts'
test = 'test'
out = 'out'
libs = ["node_modules", "lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
verbosity = 2
via_ir = true

[fuzz]
runs = 100

[profile.ci]
fuzz_runs = 1000
verbosity = 4 
